### PR TITLE
Add Heat Budget Closure Example for POP2 using xgcm

### PR DESCRIPTION
**Pull request by ALDepp**

### CODE REVIEW

**Comment by dcherian** [comment]
Thanks Anna,

what's the reason for the `to_coord` functions again? It would be good to explain this.

```
gridx.diff(to_coord((dsi.cell_volume * dsi.UET), 'u', 't'),
```
Oh are you demonstrating xgcm with the "default" POP dataset? If so, i think it'd be good to say that it's for demonstration only and the metrics version is 1000x cleaner and easier.


Similarly
```
dx['WTT'] = (gridx.diff((dsx.WTT.fillna(0) * dsx.dz.drop('z_t').rename({"z_t":"z_w_top"})
                        .assign_coords(z_w_top=dsx.z_w_top)), axis="Z", boundary="extend") 
             / 
             dsx.DZT)

```
could use a comment explaining all the manipulations.

**Comment by dcherian** [comment]
```

filepath = pop_tools.DATASETS.fetch("Pac_POP0.1_JRA_IAF_1993-12-6-test.nc")
```

this file has no heat budget terms so I couldn't get it to run. Made some minor edits + fixed linting

**Review by andersy005 — APPROVED** [review]
@ALDepp, are you still working on this? If not, I'd be happy to merge this later today

**Comment by ALDepp** [comment]
@dcherian have you updated the file? should I? 
@andersy005 Let's make sure it runs (with the test data) and then we can merge.

**Comment by dcherian** [comment]
no I have not. Can you do it when you have time?

**Comment by ALDepp** [comment]
Created the new dataset, this is ready to be merged imo.

**Comment by dcherian** [comment]
I guess anderson needs to update the file on the FTP server

**Comment by andersy005** [comment]
> I guess anderson needs to update the file on the FTP server

Yes, I am going to take care of the input file shortly

**Comment by andersy005** [comment]
Just learned the hard that force pushing on a remote repository is a bad idea -:). Anna-Lena is going to open a new PR shortly....

**Pull request closed without merging**
