### PR TITLE
made sample notebook to demonstrate xgcm capabilities

### PR DESCRIPTION
**Pull request by ALDepp**
added a sample notebook to demonstrate xgcm capabilities for calculating divergence curl and gradient

### CODE REVIEW

**Comment by ALDepp** [comment]
the sample data is here /glade/u/home/deppenme/Pac_POP0.1_JRA_IAF_1993-12-6-test.nc

**Comment by dcherian** [comment]
@andersy005 I am thinking that we merge this once @andersy005 has the data uploaded to FTP. 

Assuming that the website updates automatically, everyone on the section meeting call tomorrow should be able to easily scroll through and look at things.

**Comment by andersy005** [comment]
> the sample data is here `/glade/u/home/deppenme/Pac_POP0.1_JRA_IAF_1993-12-6-test.nc`

Where is `Pac_grid_pbc_1301x305x62.tx01_62l.2013-07-13.nc` located at?

**Comment by dcherian** [comment]
Two things came to mind:

1. we should get rid of the `nlon`, `nlat` renaming.
2. we should a line to `https://github.com/NCAR/pop-tools/blob/master/docs/source/examples.rst`

**Comment by ALDepp** [comment]
> > the sample data is here `/glade/u/home/deppenme/Pac_POP0.1_JRA_IAF_1993-12-6-test.nc`
> 
> Where is `Pac_grid_pbc_1301x305x62.tx01_62l.2013-07-13.nc` located at?

**Comment by ALDepp** [comment]
> > the sample data is here `/glade/u/home/deppenme/Pac_POP0.1_JRA_IAF_1993-12-6-test.nc`
> 
> Where is `Pac_grid_pbc_1301x305x62.tx01_62l.2013-07-13.nc` located at?

I just put it in my home on glade, same location as the data file

**Comment by ALDepp** [comment]
> Two things came to mind:
> 
> 1. we should get rid of the `nlon`, `nlat` renaming.
> 2. we should a line to `https://github.com/NCAR/pop-tools/blob/master/docs/source/examples.rst`

I thought I had done that =/ well I'll try again

**Comment by dcherian** [comment]
> What do you mean with the nlon nlat renaming? In the test?

your previous PR was merged (#39) so the cell that renames/drops `z_w` etc is not needed any more.

**Comment by andersy005** [comment]
> What do you mean with the nlon nlat renaming? In the test? 

I believe Deepak is referring to this cell

```python

# will be unnecessary once https://github.com/NCAR/pop-tools/pull/39 is merged
ds_ren = ds_ren.drop_dims(["nlat", "nlon"])
ds_ren
```

**Comment by dcherian** [comment]
@andersy005 Does the website update everytime a PR is merged or is a release necessary?

**Comment by andersy005** [comment]
> andersy005 Does the website update everytime a PR is merged or is a release necessary?

It's updated every time a PR is merged. 

You can also preview the PR build by clicking on the details:

Screen Shot 2020-03-25 at 9 43 07 AM

**Comment by andersy005** [comment]
Can we update the title of the notebook to be more explicit?

Here's the rendered version of the notebook: https://pop-tools--42.org.readthedocs.build/en/42/examples/pop_div_curl_xr_xgcm_metrics_compare.html

The title says `POP example`

**Comment by dcherian** [comment]
I guess we should change the title to `xgcm and POP output` or something
image

but looks great otherwise!

**Comment by ALDepp** [comment]
I changed the title, thanks for all the suggestiosn!

**Comment by andersy005** [comment]
Also, if we want to, we can suppress Matplotlib's output by adding `;` at the end of its statements. e.g. :

```python
plt.title(
    "xgcm_metric divergence @ {:d}m".format(
        int(div_xgcm_m.z_t.isel(z_t=5).values / 100)
    )
);
```

This avoids having 

```
Text(0.5, 1.0, 'xr divergence @ 55m')
```

**Comment by ALDepp** [comment]
the sample notebook has a mistake 
 
```
ds['cell_volume_u'] = ds_ren.DZU * ds_ren.DXT * ds_ren.DYT
```
should be
```
ds['cell_volume_u'] = ds_ren.DZU * ds_ren.DXU * ds_ren.DYU
```
I changed it an pushed but I don't see it here since it was merged? how do we change it now?

**Comment by andersy005** [comment]
>  how do we change it now?

We need to open another pull request. Follow the link below

https://github.com/ALDepp/pop-tools/pull/new/example_div_curl_grad_xgcm

**Comment by andersy005** [comment]
Or just head to example_div_curl_grad_xgcm branch of your folk and use the `pull request` button.

**Comment by DapengLi17** [comment]
Hi @ALDepp:
     I am Dapeng Li, a postdoc at Texas A&M University analyzing CESM POP data. Very impressive web [()](https://pop-tools.readthedocs.io/en/latest/examples/pop_div_curl_xr_xgcm_metrics_compare.html) to demonstrate xgcm and pop-tool. 
     I have a quick question on divergence calculation in your notebook. In you calculation, you normalized curl with cell area but normalized divergence with cell volume. Can you please let me know why the normalization are different for curl and divergence? 
Thanks so much for your time and work. 
Regards!
Dapeng Li

**Pull request merged**
