### PR TITLE
Add new cf-xarray demo notebook

### PR DESCRIPTION
**Pull request by dcherian**
Same code almost works on CMOR, CESM-POP, and CESM-MOM6

### CODE REVIEW

**Comment by dcherian** [comment]
@andersy005 we're getting duplicate runs here
image

**Comment by klindsay28** [comment]
In my own git repos with notebooks, I've found figure generating notebooks to be a bit of a pain to deal with, and I'm wondering how pop-tools is going to deal with this.

1) When code that the notebooks rely on is updated, you want to confirm that the notebooks still work. (Out of date documentation can be worse than no documentation.) It looks like this notebook relies on the NCAR environment. I don't see how the notebook could be rerun automatically, much less with external CI, so I think manual action is necessary. That's a pain.

2) In my own notebooks, I have found that updates to matplotlib can lead to slight changes in plots. I find that to be a pain for notebooks that are under version control. I haven't found a workflow in my own work for isolating such changes that I'm satisfied with. This can be mitigated by pinning a version of matplotlib, which it doesn't look like pop-tools is doing. But pinning a version also has the drawback of potentially running matplotlib with known bugs.

As the number of notebooks in pop-tools increases, I'm wondering if there is a recommended not-so-painful workflow for navigating these issues/tensions.

**Comment by dcherian** [comment]
The code is slightly simpler now but I've opened more upstream issues to see if we can simplify further. Let's wait on merging for a while.

@klindsay28 one solution could be to use jupyter-book to build the notebooks rather than rendering notebooks with output. That will at least check if things run but won't check that output figures are exactly the same (We'd need to make the needed datasets public though). matplotlib has an integration test suite with plugins that check for approximate equality between images.

**Comment by dcherian** [comment]
Merging since it's useful. I've disabled execution so Keith's point still stands.

**Pull request merged**
