### PR TITLE
Extend to_xgcm_grid_dataset() to support POP datasets with non canonical dimensions

### LINKED ISSUE #93: Extend `to_xgcm_grid_dataset()` to support POP datasets with non canonical dimensions
The existing utility functions used to transform POP dataset into an Xgcm compatible dataset can only handle a regular POP grid `(time, z, y, x)`. This assumption ends up being problematic when one is calling `to_xgcm_grid_dataset()` on a POP dataset with non canonical dimensions (for example, the dimensions for CESM2-SMYLE, or DPLE datasets are `(start year, lead, ensemble, z, y, x)`.

It would be nice to extend the existing functionality to allow users to use `to_xgcm_grid_dataset()` on POP datasets from SMYLE, DPLE projects... 

https://github.com/NCAR/pop-tools/blob/21fd3742743c22fdf90433b819b2c73425761549/pop_tools/xgcm_util.py#L90-L100

This request is from Who Kim who pointed out the original issue to me in an offline conversation (I'm going to Cc him once I know his GitHub handle).

### PR DESCRIPTION
**Pull request by andersy005**
- Fixes #93 
- Removes hard-coded time dim & support POP datasets with non canonical dimensions

### CODE REVIEW

**Comment by andersy005** [comment]
Cc @whokim... Do you mind trying this pull request with one of your "realistic" datasets to confirm that it works properly? 

To install pop-tools with these changes, you will need to run the following:

```bash
python -m pip install git+https://github.com/andersy005/pop-tools.git@extend-to-xgcm
```

**Review by dcherian — APPROVED** [review]
LGTM. Thanks Anderson

**Comment by dcherian** [comment]
cc @ALDepp

**Comment by whokim** [comment]
It seems working fine. Thanks Anderson and Deepak!

**Comment by andersy005** [comment]
Thanks for the confirmation, @whokim! Merging this shortly...

**Pull request merged**
