### PR TITLE
Update tests

### PR DESCRIPTION
**Pull request by mnlevy1981**
A few updates:

1. I added two tests to `test_fill.py` with `use_sor=True`

   * Note that I also refactored the way the data to be filled was calculated; I think this was a reasonable way to do it

1. Updated the conda environment files provided because out-of-the-box on my laptop I wasn't getting `netcdf4` and that was causing some xarray tests to fail

1. Increased the time circleCI will run `pytest` before spitting out an error (default is 10 minutes, I bumped it up to 45m)

Note that I'm still waiting for write access on the FTP server, so my two new tests will fail (the baselines for comparison won't be available yet). I want to make sure the rest of the tests run and everything looks okay, and once I can get the files uploaded I'll rerun the circleCI tests and take this out of "draft"

### CODE REVIEW

**Comment by mnlevy1981** [comment]
Huh, draft PRs don't trigger a CircleCI build. That's good to know... I'm going to mark this "ready for review" to trigger the tests, but I know at least two of them will fail due to missing baselines and we shouldn't merge this until everything passes.

**Review by dcherian — APPROVED** [review]
nice cleanup. Thanks.

**Comment by mnlevy1981** [comment]
Did I break CircleCI? I can't figure out how to get the tests to run.

**Comment by mnlevy1981** [comment]
We're down to a single failure in `upstream-dev`, and @dcherian is going to file an issue ticket with `xarray` to have this addressed upstream. If we're okay merging in a PR with a[n expected] failing test, I think this is ready to go. If we want to apply a work-around, all it takes to get the test to pass is

```
diff --git a/tests/test_eos.py b/tests/test_eos.py
index 5eb1c5a..9e58b89 100644
--- a/tests/test_eos.py
+++ b/tests/test_eos.py
@@ -40,7 +40,7 @@ def test_eos_xarray_2():

 def test_eos_ds_dask():
     fname = DATASETS.fetch('cesm_pop_monthly.T62_g17.nc')
-    ds = xr.open_dataset(fname, decode_times=False, decode_coords=False, chunks={'z_t': 20})
+    ds = xr.open_dataset(fname, decode_times=False, decode_coords=False, chunks={'z_t': 60})
     rho = pop_tools.eos(ds.SALT, ds.TEMP, depth=ds.z_t * 1e-2)
     assert isinstance(rho, xr.DataArray)
```

But then we should probably change the test back once the upstream fix is in place.

**Comment by mnlevy1981** [comment]
Rather than change the test to maintain a pass, I updated `eos.py` to rechunk `pressure` because it didn't respect the chunking in `depth` when it was computed:

```
diff --git a/pop_tools/eos.py b/pop_tools/eos.py
index 6e59f29..1ee59fd 100644
--- a/pop_tools/eos.py
+++ b/pop_tools/eos.py
@@ -100,6 +100,8 @@ def eos(salt, temp, return_coefs=False, **kwargs):
         salt = xr.where(salt > smax, smax, salt)

         salt, temp, pressure = xr.broadcast(salt, temp, pressure)
+        if isinstance(salt.data, dask.array.Array):
+            pressure = pressure.chunk(salt.chunks)

         if return_coefs:
             RHO, dRHOdS, dRHOdT = _compute_eos_coeffs(salt, temp, pressure)
```

I assume this was being done under the covers in the `apply_ufunc()` call in older versions of `xarray` and the initial reaction in https://github.com/pydata/xarray/issues/4372 make me think that maybe we should have been doing this ourselves instead of relying on `apply_ufunc()` all along.

I do have a question regarding this fix: did I add the `pressure.chunk()` call in the right place? The other option would have been right before the call to `apply_ufunc()` but I thought maybe we should get the chunks correct before the call to `_compute_eos_coeffs()`

**Comment by dcherian** [comment]
Ya I think your solution is in the right place :+1:

**Pull request merged**
